#!/usr/bin/env python3
"""
Convert PNG logo to C header in RGB565 format.
Scales logo to fit within flash partition limits.
"""

from PIL import Image
import sys

# Input logo path
LOGO_PATH = "/home/cavac/src/tanmatsu/tanmatsulogo.png"

# Output header path
OUTPUT_PATH = "main/logo_image.h"

# Target maximum width (will scale proportionally)
MAX_WIDTH = 400

def rgb888_to_rgb565(r, g, b):
    """Convert 24-bit RGB to 16-bit RGB565 format."""
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5

def main():
    print(f"Loading logo from {LOGO_PATH}...")
    logo = Image.open(LOGO_PATH).convert("RGBA")
    original_width, original_height = logo.size

    print(f"Original logo size: {original_width}x{original_height}")

    # Scale down if necessary
    if original_width > MAX_WIDTH:
        scale_factor = MAX_WIDTH / original_width
        new_width = MAX_WIDTH
        new_height = int(original_height * scale_factor)
        print(f"Scaling to {new_width}x{new_height} (scale factor: {scale_factor:.2f})")
        logo = logo.resize((new_width, new_height), Image.Resampling.LANCZOS)
    else:
        new_width = original_width
        new_height = original_height

    logo_width, logo_height = logo.size

    # Flatten transparency onto black background
    black_bg = Image.new("RGB", (logo_width, logo_height), (0, 0, 0))
    black_bg.paste(logo, (0, 0), logo)

    # Convert to RGB565
    print("Converting to RGB565 format...")
    pixels = black_bg.load()
    rgb565_data = []

    for y in range(logo_height):
        for x in range(logo_width):
            r, g, b = pixels[x, y]
            rgb565 = rgb888_to_rgb565(r, g, b)
            rgb565_data.append(rgb565)

    # Generate C header file
    print(f"Writing C header to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, 'w') as f:
        f.write("// Auto-generated Tanmatsu logo image\n")
        f.write(f"// Size: {logo_width}x{logo_height}, Format: RGB565 (16-bit)\n")
        f.write("// Generated by convert_logo.py\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define LOGO_WIDTH  {logo_width}\n")
        f.write(f"#define LOGO_HEIGHT {logo_height}\n\n")
        f.write("// RGB565 pixel data (16-bit per pixel)\n")
        f.write(f"static const uint16_t logo_image_data[{len(rgb565_data)}] = {{\n")

        # Write data in rows of 12 values for readability
        for i in range(0, len(rgb565_data), 12):
            row = rgb565_data[i:i+12]
            hex_values = ', '.join(f'0x{val:04X}' for val in row)
            f.write(f"    {hex_values},\n")

        f.write("};\n")

    # Calculate size
    size_kb = len(rgb565_data) * 2 / 1024
    print(f"\nSuccess! Generated {len(rgb565_data)} pixels ({size_kb:.1f} KB)")
    print(f"Output: {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
